#!/bin/bash

REPO_NAME="cc-repo"
COMMON_SCRIPT_PATH=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
REPO_PATH=$(echo "${COMMON_SCRIPT_PATH}" | sed -n "s|\(.*$REPO_NAME\).*|\1|p")
CONFIG_DIRECTORY="${REPO_PATH}/config"
TMP_PATH="${REPO_PATH}/tmp"
DOCKERFILE_DIRECTORY="${REPO_PATH}/setup/build"
DOCKERFILE_PATH="${DOCKERFILE_DIRECTORY}/Dockerfile"
HOST_CONFIG_FILE_NAME="host_config.sh"
HOST_CONFIG_FILE_PATH="${DOCKERFILE_DIRECTORY}/${HOST_CONFIG_FILE_NAME}"
CUSTOM_SCRIPT_PATH=""
PATH_NAME="\$PATH"
PROTO2_VERSION="2.6.1"
REQUIRED_PACKAGES=(
      "autoconf"
      "automake"
      "build-essential"
      "lsb-release"
      "software-properties-common"
      "gnupg"
      "sudo"
      "ssh"
      "neovim"
      "g++"
      "make"
      "cmake"
      "git"
      "wget"
      "curl" 
      "unzip"
      "tar"
      "bc" 
      "python3"
      "python3-pip"
      "protobuf-compiler"
      "libprotobuf-dev" 
      "docker.io"
      "gettext"
      "ca-certificates"
      "neofetch"
      "libboost-all-dev"
      "libgtest-dev"
      "libspdlog-dev"
      "libkrb5-dev"
      "libssl-dev"
      "openssl"
      "libtool"
    )
BUILD_DIR="${REPO_PATH}/build"
DEV_DOCKER_IMAGE_NAME="warp-drive-container"
DOCKER_BUILD_ARGS="--progress=plain"
DOCKER_NETWORK="dev_network"
DEV_DOCKER_NAME="warp-drive-dev"
DOCKER_SOCKET="/var/run/docker.sock"
EXPOSED_PORT="9042"
DATA_DIRECTORY="$(realpath "${REPO_PATH}/../")/warp-drive-data"
BINARIES_DIRECTORY="${REPO_PATH}/setup/scripts/bin"
CLANG_VERSION="19"

# Templates
TEMPLATE_DIRECTORY="${REPO_PATH}/setup/templates"

DEV_ENV_DOCKERFILE_TEMPLATE="Dev_Env_Dockerfile_Template"
DEV_ENV_DOCKERFILE_NAME="Dockerfile"

HOST_CONFIG_TEMPLATE="Host_Config_Template"
HOST_CONFIG_NAME="host_config.sh"

STARTUP_SCRIPT_TEMPLATE="Startup_Script_Template"
STARTUP_SCRIPT_NAME="startup_script.sh"

OS="debian:bullseye-slim"
WORKSPACE_DIR="/workspaces/${REPO_NAME}"
WORKSPACE_PARENT_DIR="/workspaces"
USER="dev"
USER_HOME="/home/${USER}"
PASSWORD="dev"
INTERNAL_HOST_CONFIG_FILE_PATH="${USER_HOME}/${HOST_CONFIG_FILE_NAME}"
DOCKER_SHELL="bash"
DOCKER_SHELL_PATH="/bin/${DOCKER_SHELL}"
RCFILE=".${DOCKER_SHELL}rc"

DEV_DOCKER_RUN_ARGS=" --rm --name=${DEV_DOCKER_NAME} --network=${DOCKER_NETWORK} -v ${DOCKER_SOCKET}:${DOCKER_SOCKET} -v ${REPO_PATH}:${WORKSPACE_DIR}"
GITHUB_DOCKER_RUN_ARGS=" --rm --name=${DEV_DOCKER_NAME} --entrypoint=\"\" --network=${DOCKER_NETWORK} -v ${DOCKER_SOCKET}:${DOCKER_SOCKET} -v ${GITHUB_WORKSPACE}:${WORKSPACE_DIR}"
LOCAL_DOCKER_RUN_ARGS=" --rm --name=${DEV_DOCKER_NAME} --entrypoint=\"\" --network=${DOCKER_NETWORK} -v ${DOCKER_SOCKET}:${DOCKER_SOCKET} -v ${REPO_PATH}:${WORKSPACE_DIR}"
